name: Development Release

on:
  issues:
    types: [closed]

jobs:
  package:
    name: Package
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [16]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Check out ref
        uses: actions/checkout@v2

      - name: Install node modules
        run: npm ci

      - name: Package
        run: npm run package

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: gruvbox-material-dev.vsix
          path: gruvbox-material-*.vsix

      - name: Comment on issue
        uses: ben-z/actions-comment-on-issue@1.0.2
        with:
          message: "This issue has been closed, the fix/feature will be available in the next release.\n\nTo get the update immediately, you can compile this extension from source code:\n\n**Requirements**\n\n1. [git](https://git-scm.com/)\n2. [nodejs](https://nodejs.org/en/download/)\n\n**Steps**\n\nOpen your terminal emulator and execute the following commands:\n\n1. Clone the repository: `git clone --depth 1 https://github.com/sainnhe/everforest-vscode.git && cd everforest-vscode`\n2. Install node modules: `npm ci`\n3. Compile and package this extension to a `.vsix` file: `npm run package`\n4. Install from this `.vsix` file: [How to install VS code extension manually? - Stack Overflow](https://stackoverflow.com/questions/37071388/how-can-i-install-visual-studio-code-extensions-offline)"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
