name: Development Release

on:
  issues:
    types: [closed]
  pull_request:
    types: [closed]

jobs:
  package:
    name: Package
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [16]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Check out ref
        uses: actions/checkout@v2

      - name: Install node modules
        run: npm ci

      - name: Package
        run: npm run package

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: gruvbox-material-dev.vsix
          path: gruvbox-material-*.vsix
