name: Issue Comment

on:
  issues:
    types: [closed]

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
    - uses: ben-z/actions-comment-on-issue@1.0.2
      with:
        message: "This issue has been closed, the fix/feature will be available in the next release.\n\nTo get the update immediately, you can compile this extension from source code:\n\n**Requirements**\n\n1. [git](https://git-scm.com/)\n2. [nodejs](https://nodejs.org/en/download/)\n\n**Steps**\n\nOpen your terminal emulator and execute the following commands:\n\n1. Clone the repository: `git clone --depth 1 https://github.com/sainnhe/gruvbox-material-vscode.git && cd gruvbox-material-vscode`\n2. Install node modules: `npm ci`\n3. Compile and package this extension to a `.vsix` file: `npm run package`\n4. Install from this `.vsix` file: [How to install VS code extension manually? - Stack Overflow](https://stackoverflow.com/questions/37071388/how-can-i-install-visual-studio-code-extensions-offline)\n5. Reload the window of vscode, then press Ctrl+Shift+P and execute \"Regenerate Themes\"."
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
